CREATE TABLE invite_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(64)                             NOT NULL,
    tenant_id  BIGINT                                  NOT NULL,
    role       VARCHAR(20)                             NOT NULL,
    used       BOOLEAN                                 NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_invite_tokens PRIMARY KEY (id)
);

ALTER TABLE public.invite_tokens
    ADD CONSTRAINT uc_invite_tokens_token UNIQUE (token);

ALTER TABLE public.invite_tokens
    ADD CONSTRAINT fk_invite_tokens_tenant
        FOREIGN KEY (tenant_id) REFERENCES public.tenants_company (id);

CREATE INDEX idx_invite_token ON public.invite_tokens (token);